# Generated by Django 5.1.2 on 2024-10-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_date',
        ),
    ]
