# Generated by Django 5.1.2 on 2024-10-31 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_date',
            new_name='created',
        ),
    ]
